@startuml orm
class User <<table>> {
    +int id : 用户ID
    +int cid : 班级ID
}
class Account <<table>> {
    +int id : 账户ID
    +int user_id : 用户ID
}
class Class <<table>> {
    +int id : 班级ID
}
class Role <<table>> {
    +int id : 角色ID
}

hide members
hide <<table>> circle
show <<table>> fields

User -> "1" Account : has >
Class "1" }-> "*" User : has >
User "m" <--> "m" Role

@enduml