@startuml route
skinparam roundcorner 5
skinparam handwritten true
skinparam maxmessagesize 60

skinparam sequence {
    participant underline
    arrowThickness 1
    groupBorderThickness 1
    GroupBorderColor #42b983
    groupHeaderFontColor darkorange
    GroupFontColor #e96900
    GroupBackgroundColor #42b983
    
}

footer "URL路由示意图"

participant "路由器" AS Router
collections "前置分发器" AS PRD
collections "分发器" AS D
collections "后置分发器" AS PSD

Router o<--]: 注册分发器
activate Router
[o-> Router: route($url)
Router -> Router: 解析URL
activate Router #FFBBBB
Router ->o]: apply_filter(`router\parse_url`,$url)
Router o<--]: $url
Router --> Router: URL别名处理
Router -->o]: fire(`router\beforeDispatch`,$router,$url)
deactivate Router
loop $view!=null
Router -> PRD: preDispatch($url,$router,$view)
activate PRD
PRD --> Router: $view
deactivate PRD
end

alt $view != null
[x-> Router: render($view)
else $view == null
loop $view!=null
Router -> D: dispatch($url, $router, $parsedInfo)
activate D
D --> Router: $view
deactivate D
end
end

alt $view != null
loop 所有后置分发器
Router -> PSD: postDispatch($url, $router, $view)
activate PSD
PSD --> Router
deactivate PSD
end
[x-> Router: render($view)
else $view == null
[x-> Router: respond(404)
end
deactivate Router
@enduml